import ihm
try:
    import ihm.reference
except ImportError:
    pass
import os

# If we're running from an SGE job, override the from_pubmed_id() and
# from_accession() functions to return cached values, since we don't have
# network access (needed to query PubMed or UniProt directly)

def mock_from_pubmed(cls, pubmed_id):
    return ihm.Citation(
        pmid=0,
        title='Soluble TREM2 inhibits secondary nucleation of Aβ fibrillization and enhances cellular uptake of fibrillar Aβ',
        journal='Proc Natl Acad Sci U S A', volume=119,
        page_range=('0', '0'), year=2021,
        authors=['Ketaki D. Belsare', 'Haifan Wu', 'Dibyendu Mondal', 'Annalise Bond', 'Jia Jin', 'Hyunil Jo', 
            'Addison E. Roush', 'Kala Bharath Pilla', 'Andrej Sali', 'Carlo Condello', 'William DeGrado'],
        doi='10.1073/pnas.2114486119')

# Auto-generated by util/get_accession_map.py
accession_map = {
    'Q9NZC2': {'db_code':'TREM2_HUMAN', 'sequence':
        'MEPLRLLILLFVTELSGAHNTTVFQGVAGQSLQVSCPYDSMKHWGRRKAWCRQLGEKGPCQRVVST'
        'HNLWLLSFLRRWNGSTAITDDTLGGTLTITLRNLQPHDAGLYQCQSLHGSEADTLRKVLVEVLADP'
        'LDHRDAGDLWFPGESESFEDAHVEHSISRSLLEGEIPFPPTSILLLLACIFLIKILAASALWAAAW'
        'HGQKPGTHPPSELDCGHDPGYQLQTLPGLRDT'},
    'P05067': {'db_code':'A4_HUMAN', 'sequence':
        'MLPGLALLLLAAWTARALEVPTDGNAGLLAEPQIAMFCGRLNMHMNVQNGKWDSDPSGTKTCIDTK'
        'EGILQYCQEVYPELQITNVVEANQPVTIQNWCKRGRKQCKTHPHFVIPYRCLVGEFVSDALLVPDK'
        'CKFLHQERMDVCETHLHWHTVAKETCSEKSTNLHDYGMLLPCGIDKFRGVEFVCCPLAEESDNVDS'
        'ADAEEDDSDVWWGGADTDYADGSEDKVVEVAEEEEVAEVEEEEADDDEDDEDGDEVEEEAEEPYEE'
        'ATERTTSIATTTTTTTESVEEVVREVCSEQAETGPCRAMISRWYFDVTEGKCAPFFYGGCGGNRNN'
        'FDTEEYCMAVCGSAMSQSLLKTTQEPLARDPVKLPTTAASTPDAVDKYLETPGDENEHAHFQKAKE'
        'RLEAKHRERMSQVMREWEEAERQAKNLPKADKKAVIQHFQEKVESLEQEAANERQQLVETHMARVE'
        'AMLNDRRRLALENYITALQAVPPRPRHVFNMLKKYVRAEQKDRQHTLKHFEHVRMVDPKKAAQIRS'
        'QVMTHLRVIYERMNQSLSLLYNVPAVAEEIQDEVDELLQKEQNYSDDVLANMISEPRISYGNDALM'
        'PSLTETKTTVELLPVNGEFSLDDLQPWHSFGADSVPANTENEVEPVDARPAADRGLTTRPGSGLTN'
        'IKTEEISEVKMDAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVVIATVIVITLVMLKKK'
        'QYTSIHHGVVEVDAAVTPEERHLSKMQQNGYENPTYKFFEQMQN'},

        }

if 'JOB_ID' in os.environ:
    ihm.Citation.from_pubmed_id = classmethod(mock_from_pubmed)
    if hasattr(ihm, 'reference'):
        def from_acc(cls, accession):
            return cls(accession=accession, **accession_map[accession])
        ihm.reference.UniProtSequence.from_accession = classmethod(from_acc)
